export const SearchContents = [
    { id: 1, content: "Install", path: "/EPOS_open_source/#/install"},
    { id: 2, content: "Download", path: "/EPOS_open_source/#/install"},
    { id: 3, content: "System requirements", path: "/EPOS_open_source/#/requirements-section"},
    { id: 4, content: "Architectural Design", path: "/EPOS_open_source/#/goals" },
    { id: 5, content: "Software Requirements", path: "/EPOS_open_source/#/goals" },
    { id: 6, content: "Modular Approach", path: "/EPOS_open_source/#/goals" },
    { id: 7, content: "Microservices", path: "/EPOS_open_source/#/goals" },
    { id: 8, content: "Web API", path: "/EPOS_open_source/#/goals" },
    { id: 9, content: "Client Interaction", path: "/EPOS_open_source/#/goals" },
    { id: 10, content: "Metadata", path: "/EPOS_open_source/#/goals" },
    { id: 11, content: "Data Storage", path: "/EPOS_open_source/#/goals" },
    { id: 12, content: "Authentication", path: "/EPOS_open_source/#/goals" },
    { id: 13, content: "Authorization", path: "/EPOS_open_source/#/goals" },
    { id: 14, content: "Maintainability", path: "/EPOS_open_source/#/goals" },
    { id: 15, content: "Deployability", path: "/EPOS_open_source/#/goals" },
    { id: 16, content: "Scalability", path: "/EPOS_open_source/#/goals" },
    { id: 17, content: "Security", path: "/EPOS_open_source/#/goals" },
    { id: 18, content: "Permission Access", path: "/EPOS_open_source/#/goals" },
    { id: 19, content: "Usability", path: "/EPOS_open_source/#/goals" },
    { id: 20, content: "API Documentation", path: "/EPOS_open_source/#/goals" },
    { id: 21, content: "API Versioning", path: "/EPOS_open_source/#/goals" },
    { id: 22, content: "Stateless Modules", path: "/EPOS_open_source/#/goals" },
    { id: 23, content: "Referential Integrity", path: "/EPOS_open_source/#/goals" },
    { id: 24, content: "Architectural Requirements", path: "/EPOS_open_source/#/requirements-section" },
    { id: 25, content: "System Architecture", path: "/EPOS_open_source/#/requirements-section" },
    { id: 26, content: "Core Concepts", path: "/EPOS_open_source/#/requirements-section" },
    { id: 27, content: "Modular Architecture", path: "/EPOS_open_source/#/requirements-section" },
    { id: 28, content: "DevOps Techniques", path: "/EPOS_open_source/#/requirements-section" },
    { id: 29, content: "Agile Approach", path: "/EPOS_open_source/#/requirements-section" },
    { id: 30, content: "Loose Coupling", path: "/EPOS_open_source/#/requirements-section" },
    { id: 31, content: "Data Model", path: "/EPOS_open_source/#/requirements-section" },
    { id: 32, content: "Metadata Catalogue", path: "/EPOS_open_source/#/requirements-section" },
    { id: 33, content: "Key Requirements", path: "/EPOS_open_source/#/requirements-section" },
    { id: 34, content: "System Functionalities", path: "/EPOS_open_source/#/requirements-section" },
    { id: 35, content: "Maintainability", path: "/EPOS_open_source/#/requirements-section" },
    { id: 36, content: "Refactoring", path: "/EPOS_open_source/#/requirements-section" },
    { id: 37, content: "Performance", path: "/EPOS_open_source/#/requirements-section" },
    { id: 38, content: "Integrated Assets", path: "/EPOS_open_source/#/requirements-section" },
    { id: 39, content: "Design Constraints", path: "/EPOS_open_source/#/requirements-section" },
    { id: 40, content: "AAAI - Authentication, Authorisation, and Accounting", path: "/EPOS_open_source/#/glossary" },
    { id: 41, content: "Cohesion - Cohesion refers to how well the individual elements within an application work together. Highly cohesive systems tend to be more robust, reliable, and reusable.", path: "/EPOS_open_source/#/glossary" },
    { id: 42, content: "CSV - Comma Separated Value", path: "/EPOS_open_source/#/glossary" },
    { id: 43, content: "DDSS - Data, Data products, Software, and Services", path: "/EPOS_open_source/#/glossary" },
    { id: 44, content: "Decoupling - Microservice architecture is often achieved by decoupling a monolithic application into independent modules for each business function.", path: "/EPOS_open_source/#/glossary" },
    { id: 45, content: "DOI - Digital Object Identifier", path: "/EPOS_open_source/#/glossary" },
    { id: 46, content: "EAB - External Advisory Board", path: "/EPOS_open_source/#/glossary" },
    { id: 47, content: "EIDA - European Integrated Data Archive", path: "/EPOS_open_source/#/glossary" },
    { id: 48, content: "EPOS-IP - European Plate Observing System – Implementation Phase", path: "/EPOS_open_source/#/glossary" },
    { id: 49, content: "EPOS-N - European Plate Observing System – Norway", path: "/EPOS_open_source/#/glossary" },
    { id: 50, content: "EUREF - Reference Frame Sub Commission for Europe", path: "/EPOS_open_source/#/glossary" },
    { id: 51, content: "FAIR - Data principles: Findable, Accessible, Interoperable, Reusable", path: "/EPOS_open_source/#/glossary" },
    { id: 52, content: "GLASS - Software/portal for WP10", path: "/EPOS_open_source/#/glossary" },
    { id: 53, content: "GNSS - Global Navigation Satellite System", path: "/EPOS_open_source/#/glossary" },
    { id: 54, content: "GPS - Global Positioning System", path: "/EPOS_open_source/#/glossary" },
    { id: 55, content: "ICS - Integrated Core Services", path: "/EPOS_open_source/#/glossary" },
    { id: 56, content: "ICS-C - Integrated Core Services - Central Hub", path: "/EPOS_open_source/#/glossary" },
    { id: 57, content: "ICS-D - Integrated Core Services - Distributed", path: "/EPOS_open_source/#/glossary" },
    { id: 58, content: "MoU - Memorandum of Understanding", path: "/EPOS_open_source/#/glossary" },
    { id: 59, content: "MSEED - MiniSEED (data format)", path: "/EPOS_open_source/#/glossary" },
    { id: 60, content: "ORFEUS - Observatories and Research Facilities for European Seismology", path: "/EPOS_open_source/#/glossary" },
    { id: 61, content: "PMB - Project Management Board", path: "/EPOS_open_source/#/glossary" },
    { id: 62, content: "RCN - Research Council of Norway (Forskningsrådet)", path: "/EPOS_open_source/#/glossary" },
    { id: 63, content: "RINEX - Receiver Independent Exchange Format", path: "/EPOS_open_source/#/glossary" },
    { id: 64, content: "SAC - Seismic Analysis Code (storage/file format)", path: "/EPOS_open_source/#/glossary" },
    { id: 65, content: "SeedLink - Protocol for seismic data exchange", path: "/EPOS_open_source/#/glossary" },
    { id: 66, content: "SEISAN - Earthquake analysis software", path: "/EPOS_open_source/#/glossary" },
    { id: 67, content: "TCS - Thematic Core Services", path: "/EPOS_open_source/#/glossary" },
    { id: 68, content: "WMS - Web Map Service", path: "/EPOS_open_source/#/glossary" },
    { id: 69, content: "WP - Work Package", path: "/EPOS_open_source/#/glossary" },
    { id: 70, content: "Data Provider - An organisation which produces data or metadata", path: "/EPOS_open_source/#/glossary" },
    { id: 71 , content: "Epos Data model" , path: "/EPOS_open_source/#/epos-data-model"},
    { id: 72 , content: "GeoJSON" , path: "/EPOS_open_source/#/epos-geo-json"},
    { id: 73 , content: "RESTful API " , path: "/EPOS_open_source/#/rest-api-definition"},
    { id: 74 , content: " Architecture Implementation " , path: "/EPOS_open_source/#/technical-design"},
    { id: 75 , content: " Messaging " , path: "/EPOS_open_source/#/technical-design"},
    { id: 76 , content: " Resources Service " , path: "/EPOS_open_source/#/technical-design"},
    { id: 77 , content: " External Access Service " , path: "/EPOS_open_source/#/technical-design"},
    { id: 78 , content: " Backoffice Service " , path: "/EPOS_open_source/#/technical-design"},
    { id: 79 , content: " Converter Service " , path: "/EPOS_open_source/#/technical-design"},
    { id: 80 , content: " Ingestor Service " , path: "/EPOS_open_source/#/technical-design"},
    { id: 81 , content: " Contributors  " , path: "/EPOS_open_source/#/contributors"},
    { id: 83 , content: " Meet The Team " , path: "/EPOS_open_source/#/contributors"},
    { id: 84 , content: " Available Libraries" , path: "/EPOS_open_source/#/contributors"},
    { id: 85 , content: " Meet The Team " , path: "/EPOS_open_source/#/Libraries"},
    { id: 86 , content: " Metadata Database API Library " , path: "/EPOS_open_source/#/Libraries"},
    { id: 87 , content: " Routing Framework " , path: "/EPOS_open_source/#/Libraries"},
    { id: 88 , content: " EPOS Data Model beans " , path: "/EPOS_open_source/#/Libraries"},
    { id: 89 , content: " EPOS GeoJSON Java Library " , path: "/EPOS_open_source/#/Libraries"},
    { id: 90 , content: " EPOS CovJSON Java Library " , path: "/EPOS_open_source/#/Libraries"},
    { id: 91 , content: " User Interfaces " , path: "/EPOS_open_source/#/current-component"},
    { id: 92 , content: " EPOS Platform " , path: "/EPOS_open_source/#/current-component"},
    { id: 93 , content: " EPOS Backoffice " , path: "/EPOS_open_source/#/current-component"},
    { id: 94 , content: " Microservices " , path: "/EPOS_open_source/#/current-component"},
    { id: 95 , content: " API Gateway " , path: "/EPOS_open_source/#/current-component"},
    { id: 97 , content: " Resources Service" , path: "/EPOS_open_source/#/current-component"},
    { id: 98 , content: " External Access Service" , path: "/EPOS_open_source/#/current-component"},
    { id: 99 , content: " Ingestor Service" , path: "/EPOS_open_source/#/current-component"},
    { id: 100 ,content: " Converter Service" , path: "/EPOS_open_source/#/current-component"},
    { id: 101, content: " Backoffice Service" , path: "/EPOS_open_source/#/current-component"},
    { id: 102, content: " Metadata Database" , path: "/EPOS_open_source/#/current-component"}

   
  



    
];
