name: BuildAndDeploy
on:
  push:
    branches:
      - 'main'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Build and deploy
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 24.x
      - name: Install dependencies
        run: npm install
      - name: Build project
        run: npm run build
        env:
          CI: false
      - name: Install gh-pages
        run: npm install gh-pages --save-dev
      - name: Deploy application
        run: npx gh-pages -d build
