name: BuildAndDeploy

on:
  push:
    branches:
      - 'main'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Build and deploy
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 23.x
      - name: Install dependencies
        run: npm install
      - name: Deploy application
        run: npm run deploy